### ISSUE TITLE
Incorrect results are reported

### ISSUE THREAD

**Issue by maurercw** [deblockt/cucumber-report-annotations-action#48] opened 2024-01-19 20:37 UTC
Using deblockt/cucumber-report-annotations-action@v1.13

I get conflicting results with the actual cucumber output compared to what this action is providing in the summary.

Cucumber shows me this:
```
...
Failing Scenarios:
cucumber -p cwm features/course_unlocker/course_unlocker.feature:10 # Scenario: Instructor wants to unlock the course
cucumber -p cwm features/course_unlocker/course_unlocker.feature:15 # Scenario: Instructor wants to lock the course

2 scenarios (2 failed)
10 steps (10 skipped)
```
But this action's output:
```
Run deblockt/cucumber-report-annotations-action@v1.13
  with:
    access-token: ***
    path: **/cucumber-reports.json
    show-global-summary-report: true
    check-status-on-error: failure
    check-status-on-undefined: success
    check-status-on-pending: success
    annotation-status-on-error: failure
    show-number-of-error-on-check-title: true
    number-of-test-error-to-fail-job: -1
    name: Cucumber report
  env:
    SECURITY_FILE_DIRECTORY: files
    BROWSER_HEADLESS: true
...
start to read cucumber logs using path **/cucumber-reports.json
found cucumber report /XXXXXX/results/cucumber-reports.json
Creating summary:     2 Scenarios (2 passed)
    10 Steps (2 failed, 10 skipped)
Sending cucumber annotations
Building all scenario summary
Send core scenario summary
```

Generally, if I get one pass and one fail, the summary looks correct, as well as if both pass.  So it might just be the "all scenarios fail" case that isn't being parsed correctly?

Attaching my json file for reference, in case it's helpful.
[cucumber-reports.json](https://github.com/deblockt/cucumber-report-annotations-action/files/13994252/cucumber-reports.json)

**Comment by deblockt** [comment] 2024-01-21 12:01
Hi, 

I juste check the json report. 
The issue happens because background steps are not included on scenario steps (like on java cucumber report), so scenario are not marked as failed. 
Reading the JSON report, I can not see any link between background elements and scenario elements. 

Using ruby, have you a choice between multiple json file format? 
Can you send me the `.feature` file associated with this report? 

Thanks

**Comment by maurercw** [comment] 2024-01-22 20:34
As far as I can tell, I only specify json as a format and have no additional control over what happens inside it.  Although, it looks like I can pass a fully qualified class name of a custom formatter.  Are you aware of something different/better than what comes default with cucumber?
Also, the usage docs seem to be directing folks away from the json format...
```
json     : Prints the feature as JSON.
              The JSON format is in maintenance mode.
              Please consider using the message formatter
              with the standalone json-formatter
              (https://github.com/cucumber/cucumber/tree/master/json-formatter).
message  : Prints each message in NDJSON form, which can then be consumed by other tools.

```
That link is wrong as it appears the repo has moved - https://github.com/cucumber/json-formatter

Anyway, here's my feature file: 
[course_unlocker.feature.txt](https://github.com/deblockt/cucumber-report-annotations-action/files/14015126/course_unlocker.feature.txt)

**Comment by maurercw** [comment] 2024-01-22 20:42
You also mentioned java, so maybe that's what you are using this for, but I can also use junit as a format, in case you wanted to include that as an input option.  Not sure if that is on your roadmap or not!  But, here's that xml file just for giggles:
[TEST-features-course_unlocker-course_unlocker.xml.txt](https://github.com/deblockt/cucumber-report-annotations-action/files/14015249/TEST-features-course_unlocker-course_unlocker.xml.txt)

**Comment by deblockt** [comment] 2024-02-04 15:26
The cucumber report annotation don't allow to publish junit report. 
I think that you can use https://github.com/marketplace/actions/junit-report-action. 

Have you a project to reproduce your issue? I'm not familiar with ruby, a project to reproduce the issue can help me. 

Thanks

**Comment by deblockt** [comment] 2024-02-04 15:39
Reading cucumber documentation I can see that json format is not supported anymore  by cucumber.
The new format is "message" can you generate a report using "message" format using ruby?

**Comment by deblockt** [comment] 2024-03-21 20:54
You can try with version 1.15 and using cucumber message format (with extension .ndjson) see https://github.com/deblockt/cucumber-report-annotations-action/tree/v1.15?tab=readme-ov-file#supported-formats

**Closed** 2024-04-19 06:46 UTC
